services:
  web:
    build:
      context: .
    ports:
      - ${APP_PORT:-5000}:5000
    volumes:
      - ./:/usr/src/app
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "root:root@tcp(mariadb)/${DB_NAME}"
      DATABASE_TEST_URL: "root:root@tcp(mariadb)/${DB_TEST_NAME}"
      DB_TEST_NAME: ${DB_TEST_NAME}
    networks:
      - app
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: goapp
      MARIADB_PASSWORD: secret
    networks:
      - app
networks:
  app:
    driver: bridge